#!/bin/bash

dirs="$HOME/bin $HOME/lib $HOME/.bashdir $HOME/.emacs.d"

# Defaults if no args
doCheck=true
doMerge=false
doPull=false
doStatus=false

saveCwd=${CWD}

if [ "$1" = "-check" ]; then
    doCheck=true
    doMerge=false
    doPull=false
    doStatus=false
fi
if [ "$1" = "-merge" ]; then
    doCheck=false
    doMerge=true
    doPull=false
    doStatus=false
fi
if [ "$1" = "-pull" ]; then
    doCheck=false
    doMerge=false
    doPull=true
    doStatus=false
fi
if [ "$1" = "-status" ]; then
    doCheck=false
    doMerge=false
    doPull=false
    doStatus=true
fi

for d in ${dirs}; do
    echo
    cd "$d"
    echo ----- "$(pwd)" ----
    if [ ${doCheck} = true ]; then
        echo "> git remote -v update"
                git remote -v update
        echo "> git status | head -2 | tail -1"
                git status | head -2 | tail -1
        echo "> git log HEAD..origin/master --oneline"
                git log HEAD..origin/master --oneline
        echo "> git diff --name-only origin/master"
                git diff --name-only origin/master
    fi
    if [ ${doMerge} = true ]; then
        echo "> git merge origin/master"
                git merge origin/master
        echo "> git status"
                git status
    fi
    if [ ${doPull} = true ]; then
        echo "> git pull"
                git pull
        echo "> git status"
                git status
    fi
    if [ ${doStatus} = true ]; then
        echo "> git status"
                git status
    fi
done

cd ${saveCwd}
