#!/bin/env bash
#
# FILE
#     digiport - connect to digiport server using telnet.
#
# SYNOPSIS
#     digiport [-p <port>] [-h <host>] [-t <title>]
#
# OPTIONS
#     -p <port> = digiserver port number (default = 2001)
#     -h <host> = host name or IP address of the digiserver
#     -t <title> = a string to place in the window title bar
#
# DESCRIPTION
#     Connects to a digiport using telnet and optionally
#     titles the window.
#
# EXAMPLE
#     digiport -h 172.20.11.5 -p 2002 -title "CIC slot 1"
#
# ENVIRONMENT
#     Nothing special required
#
# BUGS
#     No known bugs.
#
# -----------------------------------------------------------

# Main body of script. 
#
main ()
{
    # set to call exitClean on SIGINT(2) or SIGTERM(15)
    trap 'exitClean 1' INT TERM

    # load utility functions
    . utils.bash

    phoung_digiport=172.20.11.5
    howie_digiport=172.20.11.6
    defaultHost=${howie_digiport}

    # root dbps
    
    # parse arguments
    while [ $# -gt 0 ]; do

        case $1 in
        -help|-\?)
            usage
            exitClean 0;;
        -p)
            port=$2
            shift;;
        -h)
            host=$2
            shift;;
        -t)
            title=$2
            shift;;
        -*|*)
            stdErr Invalid option \"$1\". Type -help for options.
            exitClean 1;;
        esac

        shift
    done

    # if no host specified, use default
    if [ "${host}" = "" ]; then
        host=${defaultHost}
    fi

    # set title if specified
    if [ "${title}" != "" ]; then
        echo -e "\033]0;"${title}"\007"
    fi

    echo telnet ${host} ${port}
    exec telnet ${host} ${port}

    # clean up an exit
    exitClean 0
}

# -----------------------------------------------------------
#
# Clean up any resources that were reserved (temporary files, etc), then exit
# with the passed exit status.
#
exitClean ()
{
    # exit with passed exit status (if not specified, default to 1)
    exit ${1:-1}
}

# -----------------------------------------------------------
#
# Invoke the main body of the script. This must appear at the bottom of
# the script so all functions are visible to main().
#
main "$@"
