#!/usr/bin/env bash
# Prefer to use !/bin/bash but if scripts are to run on w/MacOS
# they need to !/usr/bin/env bash to avoid outdated Apple utils.

SD="Diff file you modified but but haven’t yet run git add"

case "$1" in
    "-h") showHelp=1;    shift;;
    "-n") showCmdOnly=1; shift;;
esac

if [ -v showHelp ]; then
    echo "${SD}"
    echo "Usage:"
    echo "${0##*/} <file name>"
    exit 1
fi

echo "git diff $1"

if [ -v showCmdOnly ]; then
    exit 1
fi

git diff $1
