#!/bin/bash

SD="Tell submodules to track to their branch, fix detached heads"

case "$1" in
    "-h") showHelp=1;    shift;;
    "-n") showCmdOnly=1; shift;;
esac

if [ -v showHelp ]; then
    echo "${SD}"
    echo "Usage:"
    echo "${0##*/}"
    echo "    No options"
    exit 1
fi

echo "git submodule foreach --recursive \
    'git checkout \$(git config -f \$toplevel/.gitmodules submodule.\$name.branch || echo master) || : '"

if [ -v showCmdOnly ]; then
    exit 1
fi

git submodule foreach --recursive \
    'git checkout $(git config -f $toplevel/.gitmodules submodule.$name.branch || echo master) || : '
