#!/usr/bin/env bash
# Prefer to use !/bin/bash but if scripts are to run on w/MacOS
# they need to !/usr/bin/env bash to avoid outdated Apple utils.

SD="List the files involved in latest commit or specify a commit"

case "$1" in
    "-h") showHelp=1;    shift;;
    "-n") showCmdOnly=1; shift;;
esac

if [ -v showHelp ]; then
    echo "${SD}"
    echo "Usage:"
    echo "${0##*/} [commit]"
    echo "    specify a commit or leave blank for latest"
    exit 1
fi

echo "git show --name-only $@"

if [ -v showCmdOnly ]; then
    exit 1
fi

git show --name-only "$@"
