#!/usr/bin/env bash
# Prefer to use !/bin/bash but if scripts are to run on w/MacOS
# they need to !/usr/bin/env bash to avoid outdated Apple utils.

SD="See how file looked at specific commint without modifying workspace"

case "$1" in
    "-h") showHelp=1;    shift;;
    "-n") showCmdOnly=1; shift;;
esac

if [ -v showHelp ]; then
    echo "${SD}"
    echo "Usage:"
    echo "${0##*/} <rev or commit id> <file name>"
    echo "ex: git show @{2} docs-src/conf.py       # 2 prev revs"
    echo "ex: git show 856d773fe4 docs-src/conf.py # at commit"
    exit 1
fi

echo "git show $1:$2"

if [ -v showCmdOnly ]; then
    exit 1
fi

git show $1:$2
