#!/usr/bin/env bash
# Prefer to use !/bin/bash but if scripts are to run on w/MacOS
# they need to !/usr/bin/env bash to avoid outdated Apple utils.

SD="Switch to specified branch and update submodules accordingly"

case "$1" in
    "-h") showHelp=1;    shift;;
    "-n") showCmdOnly=1; shift;;
esac

if [ -v showHelp ]; then
    echo "${SD}"
    echo "Usage:"
    echo "${0##*/} [options]"
    echo "    option to git pull cmd"
    exit 1
fi

echo "git checkout $1 --recurse-submodules"

if [ -v showCmdOnly ]; then
    exit 1
fi

git checkout $1 --recurse-submodules
