#!/usr/bin/env bash
# Prefer to use !/bin/bash but if scripts are to run on w/MacOS
# they need to !/usr/bin/env bash to avoid outdated Apple utils.

SD="Remove all from index/staging area. Opposite of git add -A."
SD="$SD Does not undo file changes. They just go back to workspace."

case "$1" in
    "-h") showHelp=1;    shift;;
    "-n") showCmdOnly=1; shift;;
esac

if [ -v showHelp ]; then
    echo "${SD}"
    echo "Usage:"
    echo "${0##*/}"
    echo "    No options"
    exit 1
fi

echo "git reset HEAD"

if [ -v showCmdOnly ]; then
    exit 1
fi

git reset HEAD
