#!/usr/bin/env bash
# Prefer to use !/bin/bash but if scripts are to run on w/MacOS
# they need to !/usr/bin/env bash to avoid outdated Apple utils.

SD="Bring local branch up to date with remote branch.
Fetches origin/branch and performs a rebase. Use this 
when you collaborate with colleague on same branch."

case "$1" in
    "-h") showHelp=1;    shift;;
    "-n") showCmdOnly=1; shift;;
esac

if [ -v showHelp ]; then
    echo "${SD}"
    echo "Usage:"
    echo "${0##*/}"
    exit 1
fi

branch=$(git rev-parse --abbrev-ref HEAD)

echo "git pull origin ${branch} --rebase"

if [ -v showCmdOnly ]; then
    exit 1
fi

git pull origin ${branch} --rebase
