#!/bin/bash
# --------------------------------------------------
  
# Print the path dirs separated by newlines

echo ${PATH} | sed -e 's/:/\
/g'

# --------------------------------------------------
