#!/usr/local/bin/expect -f
#
# rlogs into host "harp" and sends files <arg 1..n> to 
#	/usr/users/vw/fpp3
# ----------------------------------------------------

# Uncomment next line for debug
# exp_internal 1

set harp       128.1.2.17
set dest       /usr/users/vw/fpp3
set pwd_dir    [pwd]

spawn rlogin $harp
expect *howie>

set count 0
while { $count < $argc } {
    set fname [lindex $argv $count]
#   If the first character is not a "/" (absolute pathname) 
#   then prepend the working directory. string first returns an
#   index of 0 if it matches a / in postion 0.
    if [ string first / $fname ] {
        set fname $pwd_dir/$fname
    }

    send "cp $fname $dest\r"
    expect *howie>
    incr count
}

send "exit\r"
puts "\r\n"
